"""Seed the TemplateCache with 300+ high-quality query-response pairs."""

import asyncio
import sys
from dotenv import load_dotenv

load_dotenv()

from templatecache.modules.cache_store import CacheStore
from templatecache.modules.cluster_router import ClusterRouter
from templatecache.modules.router import IntentRouter

EXAMPLES = [
    # ── GREETING (short) ──────────────────────────────────────────────
    {"intent_id": "greeting", "query": "Hi", "response": "Hello! How can I help you today?"},
    {"intent_id": "greeting", "query": "Hey there", "response": "Hi there! What can I do for you?"},
    {"intent_id": "greeting", "query": "Good morning", "response": "Good morning! How may I assist you?"},
    {"intent_id": "greeting", "query": "Hello", "response": "Hello! What would you like to know?"},
    {"intent_id": "greeting", "query": "Howdy", "response": "Hey! I'm here to help. What's on your mind?"},

    # ── FAREWELL (short) ──────────────────────────────────────────────
    {"intent_id": "farewell", "query": "Bye", "response": "Goodbye! Have a great day!"},
    {"intent_id": "farewell", "query": "See you later", "response": "See you! Feel free to come back anytime."},
    {"intent_id": "farewell", "query": "Thanks, bye", "response": "You're welcome! Take care!"},

    # ── DEFINITION (short) ────────────────────────────────────────────
    {"intent_id": "definition", "query": "What is an API?", "response": "An API (Application Programming Interface) is a set of rules and protocols that allows different software applications to communicate with each other."},
    {"intent_id": "definition", "query": "What is a database?", "response": "A database is an organized collection of structured data stored electronically, designed for efficient retrieval, insertion, and management of information."},
    {"intent_id": "definition", "query": "What is machine learning?", "response": "Machine learning is a branch of artificial intelligence where systems learn patterns from data and improve their performance on tasks without being explicitly programmed."},
    {"intent_id": "definition", "query": "What is an algorithm?", "response": "An algorithm is a step-by-step set of instructions designed to perform a specific task or solve a particular problem."},
    {"intent_id": "definition", "query": "What is encryption?", "response": "Encryption is the process of converting readable data into an encoded format that can only be decoded by someone with the correct decryption key."},

    # ── HOW_IT_WORKS (detailed) ───────────────────────────────────────
    {"intent_id": "how_it_works_http", "query": "Explain how HTTP requests work",
     "response": "When you type a URL into your browser, it sends an HTTP request to the server hosting that website. The request includes a method (GET, POST, PUT, DELETE), headers with metadata, and optionally a body with data. The server processes the request, interacts with databases or other services as needed, and returns an HTTP response containing a status code (like 200 for success or 404 for not found), response headers, and the requested content. The browser then renders this content for you to see."},
    {"intent_id": "how_it_works_dns", "query": "Describe how DNS resolution works",
     "response": "DNS resolution translates human-readable domain names into IP addresses. When you enter a URL, your browser first checks its local cache. If not found, it queries a recursive DNS resolver (usually your ISP's). The resolver checks its cache, then queries root nameservers, which direct it to TLD nameservers (.com, .org), which point to the authoritative nameserver for the domain. The authoritative server returns the IP address, which propagates back through the chain and gets cached at each level for future lookups."},
    {"intent_id": "how_it_works_git", "query": "Explain how Git version control works",
     "response": "Git tracks changes to files using a directed acyclic graph of commits. Each commit is a snapshot of your entire project with a unique SHA-1 hash, a pointer to its parent commit(s), and metadata. Branches are lightweight pointers to specific commits. When you stage changes with 'git add', files move to the staging area. 'git commit' creates a new snapshot. Merging combines branch histories, while rebasing replays commits onto a new base. The distributed nature means every clone has the full history, enabling offline work and redundancy."},
    {"intent_id": "how_it_works_tls", "query": "Describe how TLS encryption works in detail",
     "response": "TLS (Transport Layer Security) secures internet communication through a handshake process. First, the client sends a ClientHello with supported cipher suites and a random number. The server responds with its certificate and chosen cipher suite. The client verifies the certificate against trusted CAs, then both sides generate a shared secret using asymmetric encryption (like RSA or ECDHE). This shared secret derives symmetric session keys for encrypting actual data. All subsequent communication uses fast symmetric encryption (like AES), with message authentication codes ensuring data integrity."},
    {"intent_id": "how_it_works_jwt", "query": "Explain how JWT authentication works",
     "response": "JSON Web Tokens (JWT) provide stateless authentication. When a user logs in, the server creates a token with three parts: a header (algorithm and type), a payload (user claims like ID, role, expiration), and a signature (header + payload signed with a secret key). The token is base64url-encoded and sent to the client. On subsequent requests, the client sends the JWT in the Authorization header. The server verifies the signature without needing a database lookup, extracts the claims, and grants or denies access based on the payload contents."},

    # ── PROGRAMMING_CONCEPT (detailed) ────────────────────────────────
    {"intent_id": "concept_recursion", "query": "Explain recursion in programming",
     "response": "Recursion is when a function calls itself to solve a problem by breaking it into smaller, identical subproblems. Every recursive function needs a base case (the simplest version that returns directly) and a recursive case (which reduces the problem and calls itself). For example, calculating factorial: factorial(5) calls factorial(4), which calls factorial(3), and so on until factorial(1) returns 1. The call stack stores each incomplete call until the base case is reached, then results propagate back up. Recursion is elegant for tree traversals, divide-and-conquer algorithms, and problems with self-similar structure, but can cause stack overflow if the base case isn't reached."},
    {"intent_id": "concept_oop", "query": "Describe object-oriented programming",
     "response": "Object-oriented programming (OOP) organizes code around objects — instances of classes that bundle data (attributes) and behavior (methods). The four pillars are: Encapsulation (hiding internal state behind public interfaces), Inheritance (creating new classes from existing ones to reuse code), Polymorphism (allowing objects of different classes to respond to the same method call), and Abstraction (exposing only essential features while hiding complexity). OOP models real-world entities naturally: a Car class might have attributes like speed and color, and methods like accelerate() and brake(). This paradigm promotes modularity, reusability, and maintainability in large codebases."},
    {"intent_id": "concept_async", "query": "Explain how async/await works",
     "response": "Async/await enables non-blocking concurrent execution. When a function is declared async, it returns a coroutine instead of executing immediately. The await keyword pauses the coroutine at I/O-bound operations (network requests, file reads) and yields control back to the event loop, which can run other coroutines. When the awaited operation completes, the coroutine resumes from where it paused. This differs from threading because it uses a single thread with cooperative multitasking — no race conditions or locks needed. It's ideal for I/O-heavy workloads like web servers handling thousands of simultaneous connections."},
    {"intent_id": "concept_closure", "query": "Explain closures in programming",
     "response": "A closure is a function that captures and remembers variables from its enclosing scope, even after that scope has finished executing. When an inner function references a variable from an outer function, that variable's binding is preserved in the closure. For example, a make_counter() function can return an inner increment() function that keeps access to a count variable. Each call to make_counter() creates a separate closure with its own count. Closures enable data privacy, function factories, and callback patterns. They're fundamental to functional programming and used heavily in JavaScript, Python, and Swift."},

    # ── DATA_STRUCTURES (list) ────────────────────────────────────────
    {"intent_id": "list_data_structures", "query": "List the main data structures in computer science",
     "response": "1. Arrays — fixed-size sequential collections with O(1) index access\n2. Linked Lists — dynamic chains of nodes with O(1) insertion/deletion\n3. Stacks — LIFO collections supporting push and pop\n4. Queues — FIFO collections supporting enqueue and dequeue\n5. Hash Tables — key-value stores with O(1) average lookup\n6. Trees — hierarchical structures (binary trees, BSTs, AVL, red-black)\n7. Heaps — priority-based tree structures for min/max retrieval\n8. Graphs — networks of nodes and edges for modeling relationships\n9. Tries — prefix trees optimized for string searching\n10. Sets — unordered collections of unique elements"},
    {"intent_id": "list_sort_algos", "query": "What are the main sorting algorithms?",
     "response": "1. Bubble Sort — O(n²), repeatedly swaps adjacent elements\n2. Selection Sort — O(n²), finds minimum and places it at the front\n3. Insertion Sort — O(n²), builds sorted array one element at a time\n4. Merge Sort — O(n log n), divide-and-conquer with stable merging\n5. Quick Sort — O(n log n) average, partition-based with pivot selection\n6. Heap Sort — O(n log n), uses heap data structure\n7. Counting Sort — O(n+k), non-comparison sort for integer ranges\n8. Radix Sort — O(nk), sorts digit by digit\n9. Tim Sort — O(n log n), hybrid merge+insertion used in Python/Java\n10. Shell Sort — O(n log²n), improved insertion sort with gap sequences"},
    {"intent_id": "list_design_patterns", "query": "List the most important software design patterns",
     "response": "1. Singleton — ensures a class has only one instance\n2. Factory Method — creates objects without specifying exact class\n3. Observer — notifies dependents when state changes\n4. Strategy — encapsulates interchangeable algorithms\n5. Decorator — adds behavior to objects dynamically\n6. Adapter — bridges incompatible interfaces\n7. Builder — constructs complex objects step by step\n8. Command — encapsulates requests as objects\n9. Repository — abstracts data storage and retrieval\n10. MVC — separates model, view, and controller concerns"},
    {"intent_id": "list_http_methods", "query": "What are the HTTP methods?",
     "response": "1. GET — retrieve a resource\n2. POST — create a new resource\n3. PUT — replace a resource entirely\n4. PATCH — partially update a resource\n5. DELETE — remove a resource\n6. HEAD — GET without response body (check headers)\n7. OPTIONS — describe communication options for a resource\n8. TRACE — loop-back test along the path to the resource\n9. CONNECT — establish a tunnel to the server"},
    {"intent_id": "list_python_features", "query": "List the key features of Python",
     "response": "1. Dynamic typing — no type declarations required\n2. Interpreted — runs without compilation step\n3. Garbage collection — automatic memory management\n4. List comprehensions — concise collection transformations\n5. Generators — lazy evaluation with yield\n6. Decorators — modify functions with @syntax\n7. Multiple inheritance — classes can extend multiple parents\n8. Duck typing — objects defined by behavior, not class\n9. Context managers — resource handling with 'with' statements\n10. Rich standard library — batteries included philosophy"},

    # ── COMPARISON (detailed) ─────────────────────────────────────────
    {"intent_id": "compare_sql_nosql", "query": "Compare SQL and NoSQL databases",
     "response": "SQL databases (PostgreSQL, MySQL) use structured tables with predefined schemas, enforce ACID transactions, and excel at complex joins and queries. They scale vertically and are ideal for structured, relational data. NoSQL databases (MongoDB, Redis, Cassandra) use flexible schemas (document, key-value, column-family, or graph models), prioritize horizontal scalability, and often follow BASE (Basically Available, Soft state, Eventually consistent). NoSQL shines with unstructured data, rapid iteration, and massive scale. Choose SQL when data integrity and complex queries matter; choose NoSQL when flexibility, speed, and horizontal scaling are priorities."},
    {"intent_id": "compare_rest_graphql", "query": "Compare REST and GraphQL APIs",
     "response": "REST uses fixed endpoints (GET /users, POST /orders) where each returns a predetermined data shape, often leading to over-fetching or under-fetching. GraphQL provides a single endpoint where clients specify exactly what data they need via queries, reducing network overhead. REST relies on HTTP methods for semantics and is well-cached by CDNs. GraphQL uses POST for everything, making caching harder but offering real-time subscriptions and strong typing via schemas. REST is simpler to set up and widely understood. GraphQL excels when clients have diverse data needs, like mobile apps needing minimal payloads."},
    {"intent_id": "compare_tcp_udp", "query": "Compare TCP and UDP protocols",
     "response": "TCP (Transmission Control Protocol) is connection-oriented, guaranteeing ordered, reliable delivery with error checking, flow control, and congestion management. It uses a three-way handshake to establish connections. UDP (User Datagram Protocol) is connectionless, sending packets without delivery guarantees — no ordering, no retransmission, no handshake. TCP is used for web browsing, email, and file transfer where reliability matters. UDP is used for video streaming, gaming, DNS lookups, and VoIP where speed and low latency outweigh occasional packet loss. TCP has higher overhead; UDP has lower latency."},
    {"intent_id": "compare_docker_vm", "query": "Compare Docker containers and virtual machines",
     "response": "Virtual machines (VMs) run a full guest OS on a hypervisor, providing complete isolation but consuming significant resources (GB of RAM per VM, minutes to boot). Docker containers share the host OS kernel, packaging only the application and its dependencies. Containers start in seconds, use MB of memory, and run many more instances per host. VMs offer stronger security isolation since they have separate kernels. Containers are ideal for microservices, CI/CD pipelines, and rapid scaling. VMs suit workloads needing different OS types or maximum security isolation. Both can complement each other in production environments."},

    # ── HOW_TO (detailed) ─────────────────────────────────────────────
    {"intent_id": "howto_git_rebase", "query": "How do I rebase in Git?",
     "response": "To rebase your feature branch onto main: first, ensure your working directory is clean (commit or stash changes). Run 'git checkout feature-branch', then 'git rebase main'. Git will replay your feature branch commits one by one on top of the latest main. If conflicts arise, Git pauses and marks the conflicting files — edit them, run 'git add' on each, then 'git rebase --continue'. To abort, use 'git rebase --abort'. Interactive rebase ('git rebase -i main') lets you squash, reorder, or edit commits. After rebasing, force-push with 'git push --force-with-lease' since history was rewritten. Never rebase shared/public branches."},
    {"intent_id": "howto_ssh_keys", "query": "How do I set up SSH keys?",
     "response": "Generate a key pair with 'ssh-keygen -t ed25519 -C your@email.com'. Accept the default file location (~/.ssh/id_ed25519) and set a passphrase for security. Start the SSH agent with 'eval $(ssh-agent -s)' and add your key with 'ssh-add ~/.ssh/id_ed25519'. Copy the public key with 'cat ~/.ssh/id_ed25519.pub' and paste it into your server's ~/.ssh/authorized_keys file, or add it in your GitHub/GitLab settings. Test with 'ssh -T git@github.com'. For multiple keys, create an ~/.ssh/config file mapping hosts to specific key files."},
    {"intent_id": "howto_venv", "query": "How do I set up a Python virtual environment?",
     "response": "Create a virtual environment with 'python3 -m venv myenv'. Activate it: on macOS/Linux run 'source myenv/bin/activate', on Windows run 'myenv\\Scripts\\activate'. Your terminal prompt will change to show the active environment. Install packages with 'pip install package-name' — they'll be isolated to this environment. Save dependencies with 'pip freeze > requirements.txt'. Recreate the environment elsewhere with 'pip install -r requirements.txt'. Deactivate with 'deactivate'. Add 'myenv/' to your .gitignore. For modern projects, consider using 'poetry' or 'pipenv' which combine virtual environments with dependency management."},
    {"intent_id": "howto_docker", "query": "Walk me through creating a Dockerfile",
     "response": "Start with a base image: 'FROM python:3.12-slim'. Set the working directory: 'WORKDIR /app'. Copy dependency files first for better caching: 'COPY requirements.txt .' then 'RUN pip install --no-cache-dir -r requirements.txt'. Copy application code: 'COPY . .'. Expose the port: 'EXPOSE 8000'. Set the startup command: 'CMD [\"uvicorn\", \"app:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]'. Build with 'docker build -t myapp .'. Run with 'docker run -p 8000:8000 myapp'. Use .dockerignore to exclude node_modules, .git, and __pycache__. Multi-stage builds can reduce image size by separating build and runtime stages."},
    {"intent_id": "howto_regex", "query": "How do I write regular expressions?",
     "response": "Start with literals: 'cat' matches the word cat. Use character classes: [aeiou] matches any vowel, [0-9] matches digits. Quantifiers control repetition: * (zero or more), + (one or more), ? (zero or one), {3} (exactly 3), {2,5} (2 to 5 times). Anchors: ^ matches start of line, $ matches end. Special characters: \\d for digits, \\w for word characters, \\s for whitespace. Groups with parentheses: (abc)+ matches repeated 'abc'. Alternation: cat|dog matches either. Lookahead (?=...) asserts what follows without consuming. Always test with tools like regex101.com. In Python, use the re module: re.findall(r'\\d+', text) finds all numbers."},

    # ── MATH/SCIENCE (detailed) ───────────────────────────────────────
    {"intent_id": "explain_photosynthesis", "query": "Explain how photosynthesis works in detail",
     "response": "Photosynthesis converts light energy into chemical energy in two stages. In the light-dependent reactions (in thylakoid membranes), chlorophyll absorbs sunlight and uses it to split water molecules into oxygen, protons, and electrons. The electron transport chain generates ATP and NADPH. In the light-independent reactions (Calvin cycle, in the stroma), the enzyme RuBisCO fixes CO2 into a 3-carbon molecule. Using ATP and NADPH from stage one, this is reduced to G3P, which combines to form glucose. The overall equation: 6CO2 + 6H2O + light energy → C6H12O6 + 6O2. Temperature, light intensity, and CO2 concentration all affect the rate."},
    {"intent_id": "explain_gravity", "query": "Explain how gravity works",
     "response": "In Newtonian physics, gravity is a force between any two masses proportional to their product and inversely proportional to the square of the distance between them (F = Gm1m2/r²). Einstein's general relativity reframes gravity as the curvature of spacetime caused by mass and energy. Massive objects like Earth warp the fabric of spacetime, and other objects follow curved paths (geodesics) through this warped geometry — what we perceive as gravitational attraction. This explains phenomena Newton couldn't: gravitational lensing, time dilation near massive objects, and gravitational waves. On Earth, gravity accelerates objects at approximately 9.8 m/s²."},
    {"intent_id": "explain_evolution", "query": "Describe how evolution by natural selection works",
     "response": "Evolution by natural selection operates through four key mechanisms. First, variation exists within populations due to genetic mutations and recombination. Second, organisms produce more offspring than can survive (overproduction). Third, individuals with traits better suited to their environment are more likely to survive and reproduce (differential survival). Fourth, these advantageous traits are heritable and passed to offspring. Over generations, favorable traits become more common in the population (adaptation). Additional mechanisms include genetic drift (random changes in small populations), gene flow (migration between populations), and sexual selection. Speciation occurs when populations become reproductively isolated and diverge sufficiently."},

    # ── LISTS (various domains) ───────────────────────────────────────
    {"intent_id": "list_js_frameworks", "query": "List the popular JavaScript frameworks",
     "response": "1. React — component-based UI library by Meta\n2. Vue.js — progressive framework with gentle learning curve\n3. Angular — full-featured framework by Google\n4. Svelte — compiler-based approach with no virtual DOM\n5. Next.js — React framework with SSR and static generation\n6. Nuxt.js — Vue framework with SSR support\n7. Express.js — minimal Node.js web framework\n8. Fastify — high-performance Node.js framework\n9. Remix — full-stack React framework with nested routing\n10. Astro — static site builder with partial hydration"},
    {"intent_id": "list_cloud_services", "query": "What are the major cloud services?",
     "response": "1. AWS EC2 — virtual servers in the cloud\n2. AWS S3 — object storage\n3. AWS Lambda — serverless functions\n4. Google Cloud Run — managed container execution\n5. Google BigQuery — serverless data warehouse\n6. Azure Functions — event-driven serverless compute\n7. Azure Cosmos DB — globally distributed database\n8. Cloudflare Workers — edge computing platform\n9. Vercel — frontend deployment platform\n10. Firebase — app development platform with real-time database"},
    {"intent_id": "list_linux_commands", "query": "List essential Linux commands",
     "response": "1. ls — list directory contents\n2. cd — change directory\n3. grep — search text patterns in files\n4. find — search for files by name, type, or date\n5. chmod — change file permissions\n6. ps / top / htop — view running processes\n7. curl / wget — download files or make HTTP requests\n8. tar — archive and compress files\n9. ssh — secure remote login\n10. awk / sed — text processing and transformation"},
    {"intent_id": "list_db_types", "query": "What are the types of databases?",
     "response": "1. Relational (SQL) — PostgreSQL, MySQL, SQLite\n2. Document — MongoDB, CouchDB, Firestore\n3. Key-Value — Redis, DynamoDB, Memcached\n4. Column-Family — Cassandra, HBase, ScyllaDB\n5. Graph — Neo4j, ArangoDB, Amazon Neptune\n6. Time-Series — InfluxDB, TimescaleDB, Prometheus\n7. Search Engine — Elasticsearch, Solr, Meilisearch\n8. Vector — Pinecone, Weaviate, Qdrant\n9. Object — ObjectDB, db4o\n10. NewSQL — CockroachDB, TiDB, Spanner"},
    {"intent_id": "list_security_practices", "query": "List web security best practices",
     "response": "1. Input validation — sanitize and validate all user input\n2. Parameterized queries — prevent SQL injection\n3. HTTPS everywhere — encrypt data in transit with TLS\n4. CORS policies — restrict cross-origin requests\n5. CSRF tokens — prevent cross-site request forgery\n6. Content Security Policy — mitigate XSS attacks\n7. Rate limiting — prevent brute force and DDoS\n8. Password hashing — use bcrypt, scrypt, or Argon2\n9. JWT best practices — short expiration, secure storage\n10. Dependency scanning — audit packages for vulnerabilities"},

    # ── TROUBLESHOOTING (detailed) ────────────────────────────────────
    {"intent_id": "debug_cors", "query": "How do I fix CORS errors?",
     "response": "CORS errors occur when a browser blocks requests from one origin to another due to missing Access-Control-Allow-Origin headers. To fix: on your server, add the header 'Access-Control-Allow-Origin' with the requesting domain (or '*' for development). For preflight requests (OPTIONS), also set 'Access-Control-Allow-Methods' (GET, POST, etc.) and 'Access-Control-Allow-Headers' (Content-Type, Authorization). In Express.js, use the 'cors' middleware. In FastAPI, add CORSMiddleware. In Django, use django-cors-headers. For credentials (cookies), set 'Access-Control-Allow-Credentials: true' and specify exact origins (not '*'). Never use '*' in production with credentials."},
    {"intent_id": "debug_memory_leak", "query": "How do I find memory leaks in my application?",
     "response": "Start by monitoring memory usage over time with tools like htop, Activity Monitor, or application-level metrics. In Python, use tracemalloc to snapshot memory allocations and compare snapshots to find growth. The objgraph library visualizes object reference graphs. In JavaScript, Chrome DevTools' Memory tab offers heap snapshots and allocation timelines — take snapshots before and after operations, then compare retained sizes. Common causes: unbounded caches, event listener accumulation, circular references, global variable growth, and unclosed connections. Fix by implementing proper cleanup (context managers, removeEventListener), using weak references where appropriate, and setting cache size limits."},
    {"intent_id": "debug_slow_query", "query": "How do I optimize slow database queries?",
     "response": "First, use EXPLAIN ANALYZE to see the query execution plan and identify full table scans, missing indexes, or inefficient joins. Add indexes on columns used in WHERE, JOIN, and ORDER BY clauses. Avoid SELECT * — fetch only needed columns. Use pagination (LIMIT/OFFSET or cursor-based) instead of loading entire result sets. For N+1 query problems, use JOINs or batch loading. Consider denormalization for read-heavy workloads. Add query result caching with Redis for frequently accessed data. Monitor slow query logs and set up alerts. For complex analytical queries, consider materialized views or moving to a data warehouse."},

    # ── BEST_PRACTICES (detailed) ─────────────────────────────────────
    {"intent_id": "bestpractice_code_review", "query": "Describe best practices for code reviews",
     "response": "Keep pull requests small (under 400 lines) for thorough review. Write clear PR descriptions explaining the what and why. Review for correctness, readability, maintainability, and security — not just style (use linters for that). Ask questions instead of making demands: 'What do you think about...' rather than 'Change this to...'. Look for edge cases, error handling, and test coverage. Respond to all comments before merging. Set a 24-hour SLA for initial review. Use conventional comments (suggestion, nitpick, question, blocker) to indicate severity. Automate what you can: CI checks, formatting, type checking. Praise good patterns to reinforce learning."},
    {"intent_id": "bestpractice_api_design", "query": "Explain API design best practices",
     "response": "Use consistent, predictable URL patterns with plural nouns (/users, /orders). Use HTTP methods correctly: GET for reading, POST for creating, PUT for full updates, PATCH for partial updates, DELETE for removal. Return appropriate status codes: 200 for success, 201 for created, 400 for bad request, 401 for unauthorized, 404 for not found, 500 for server error. Version your API (/v1/users). Support pagination, filtering, and sorting. Return consistent error response shapes with error codes and messages. Use JSON for request and response bodies. Document with OpenAPI/Swagger. Implement rate limiting and authentication from day one."},
    {"intent_id": "bestpractice_testing", "query": "Describe best practices for writing tests",
     "response": "Follow the testing pyramid: many unit tests, fewer integration tests, fewest end-to-end tests. Each test should be independent, deterministic, and fast. Use the Arrange-Act-Assert pattern for clarity. Test behavior, not implementation details. Aim for meaningful coverage of critical paths, edge cases, and error conditions rather than chasing 100% coverage. Name tests descriptively: 'test_user_creation_fails_with_duplicate_email'. Mock external dependencies (APIs, databases) in unit tests. Use fixtures and factories to reduce test setup boilerplate. Run tests in CI on every push. Write tests before fixing bugs to prevent regressions."},

    # ── QUICK FACTS (short) ───────────────────────────────────────────
    {"intent_id": "fact_python_creator", "query": "Who created Python?", "response": "Python was created by Guido van Rossum and first released in 1991."},
    {"intent_id": "fact_linux_creator", "query": "Who created Linux?", "response": "Linux was created by Linus Torvalds in 1991 as a free, open-source operating system kernel."},
    {"intent_id": "fact_http_port", "query": "What port does HTTP use?", "response": "HTTP uses port 80 by default. HTTPS uses port 443."},
    {"intent_id": "fact_big_o", "query": "What is Big O notation?", "response": "Big O notation describes the upper bound of an algorithm's time or space complexity as input size grows, e.g., O(n) for linear time, O(log n) for logarithmic time."},
    {"intent_id": "fact_rest", "query": "What does REST stand for?", "response": "REST stands for Representational State Transfer, an architectural style for designing networked applications using stateless HTTP requests."},

    # ── CONVERSIONS (short) ───────────────────────────────────────────
    {"intent_id": "convert_binary", "query": "How do I convert binary to decimal?",
     "response": "Multiply each binary digit by 2 raised to its position power (starting from 0 on the right), then sum the results. For example, 1011 in binary = 1×2³ + 0×2² + 1×2¹ + 1×2⁰ = 8 + 0 + 2 + 1 = 11 in decimal."},
    {"intent_id": "convert_hex", "query": "How do I read hexadecimal?",
     "response": "Hexadecimal is base-16 using digits 0-9 and letters A-F (A=10, B=11, C=12, D=13, E=14, F=15). Each hex digit represents 4 binary bits. For example, 0xFF = 15×16¹ + 15×16⁰ = 240 + 15 = 255 in decimal. Hex is commonly used for colors (#FF5733), memory addresses, and byte values."},

    # ── ARCHITECTURE (detailed) ───────────────────────────────────────
    {"intent_id": "arch_microservices", "query": "Explain microservices architecture",
     "response": "Microservices architecture decomposes an application into small, independently deployable services, each owning its own data and business logic. Services communicate via APIs (REST, gRPC) or message queues (RabbitMQ, Kafka). Each service can be developed, tested, deployed, and scaled independently by different teams using different technologies. Benefits include fault isolation, independent scaling, and technology flexibility. Challenges include distributed system complexity, data consistency across services, network latency, and operational overhead. Key patterns: API Gateway for routing, service discovery for location, circuit breakers for fault tolerance, and saga pattern for distributed transactions."},
    {"intent_id": "arch_event_driven", "query": "Describe event-driven architecture",
     "response": "Event-driven architecture (EDA) structures applications around the production, detection, and reaction to events. Producers emit events (state changes) to a message broker (Kafka, RabbitMQ, AWS SNS). Consumers subscribe to event streams and react asynchronously. Key patterns include Event Sourcing (storing state changes as a sequence of events), CQRS (separating read and write models), and pub/sub (decoupling producers from consumers). Benefits: loose coupling, scalability, real-time processing, and natural audit trails. Challenges: eventual consistency, event ordering, debugging distributed flows, and schema evolution. EDA excels in systems requiring real-time reactions and high throughput."},

    # ── DEVOPS (detailed / list) ──────────────────────────────────────
    {"intent_id": "explain_cicd", "query": "Explain CI/CD pipelines",
     "response": "CI/CD automates the software delivery process. Continuous Integration (CI) automatically builds and tests code on every commit — developers push to a shared repository, triggering automated builds, unit tests, integration tests, linting, and security scans. If any step fails, the team is notified immediately. Continuous Delivery (CD) extends CI by automatically deploying passing builds to staging environments, requiring manual approval for production. Continuous Deployment goes further by automatically deploying every passing build to production. Tools like GitHub Actions, GitLab CI, Jenkins, and CircleCI orchestrate these pipelines. Key practices: fast feedback loops, reproducible builds, infrastructure as code, and blue-green or canary deployments for safe rollouts."},
    {"intent_id": "list_devops_tools", "query": "List essential DevOps tools",
     "response": "1. Git — version control\n2. Docker — containerization\n3. Kubernetes — container orchestration\n4. Terraform — infrastructure as code\n5. Ansible — configuration management\n6. Jenkins / GitHub Actions — CI/CD pipelines\n7. Prometheus + Grafana — monitoring and alerting\n8. ELK Stack — logging (Elasticsearch, Logstash, Kibana)\n9. Vault — secrets management\n10. ArgoCD — GitOps continuous delivery"},
    {"intent_id": "explain_kubernetes", "query": "Explain how Kubernetes works",
     "response": "Kubernetes orchestrates containerized applications across a cluster of machines. The control plane consists of an API server (entry point for all operations), etcd (distributed key-value store for cluster state), scheduler (assigns pods to nodes), and controller manager (maintains desired state). Worker nodes run a kubelet (manages pods on the node) and kube-proxy (handles networking). You define desired state in YAML manifests: Deployments specify how many pod replicas to run, Services provide stable network endpoints, ConfigMaps and Secrets manage configuration. Kubernetes continuously reconciles actual state with desired state, automatically restarting failed containers, scaling replicas, and rolling out updates with zero downtime."},

    # ── DATABASE (detailed) ───────────────────────────────────────────
    {"intent_id": "explain_acid", "query": "Explain ACID properties in databases",
     "response": "ACID properties ensure reliable database transactions. Atomicity means a transaction is all-or-nothing — if any part fails, the entire transaction rolls back. Consistency ensures the database moves from one valid state to another, enforcing constraints and rules. Isolation means concurrent transactions don't interfere with each other — different isolation levels (Read Uncommitted, Read Committed, Repeatable Read, Serializable) balance consistency vs. performance. Durability guarantees that committed transactions survive system crashes, typically using write-ahead logging (WAL). Relational databases like PostgreSQL provide strong ACID guarantees. NoSQL databases often relax some ACID properties for better performance and scalability (BASE model)."},
    {"intent_id": "explain_indexing", "query": "Explain how database indexing works",
     "response": "A database index is a data structure (typically a B-tree or hash table) that speeds up data retrieval at the cost of additional storage and slower writes. Without an index, the database must scan every row (full table scan). With an index on a column, the database can quickly locate matching rows using the sorted index structure. B-tree indexes support equality and range queries efficiently. Hash indexes are faster for exact matches only. Composite indexes cover multiple columns (order matters — leftmost prefix rule). Covering indexes include all query columns, avoiding table lookups entirely. Too many indexes slow down INSERT/UPDATE/DELETE operations. Use EXPLAIN to verify index usage."},

    # ── NETWORKING (detailed / list) ──────────────────────────────────
    {"intent_id": "list_osi_layers", "query": "List the OSI model layers",
     "response": "1. Physical — electrical signals, cables, connectors (bits)\n2. Data Link — MAC addresses, frames, switches (Ethernet, Wi-Fi)\n3. Network — IP addresses, routing, packets (IP, ICMP)\n4. Transport — end-to-end communication, segments (TCP, UDP)\n5. Session — managing connections and sessions (RPC, PPTP)\n6. Presentation — data formatting, encryption (SSL/TLS, JPEG)\n7. Application — user-facing protocols (HTTP, FTP, SMTP, DNS)"},
    {"intent_id": "explain_load_balancing", "query": "Explain how load balancing works",
     "response": "Load balancing distributes incoming traffic across multiple servers to ensure no single server becomes overwhelmed. A load balancer sits between clients and backend servers, routing requests using algorithms: Round Robin (sequential rotation), Least Connections (sends to server with fewest active connections), Weighted (assigns based on server capacity), IP Hash (same client always reaches same server for session persistence). Layer 4 load balancers route based on IP/port (faster). Layer 7 load balancers inspect HTTP content for smarter routing (path-based, header-based). Health checks continuously verify server availability. Popular tools: Nginx, HAProxy, AWS ALB, Cloudflare. Load balancers also enable zero-downtime deployments and horizontal scaling."},

    # ── LANGUAGE FEATURES (detailed) ──────────────────────────────────
    {"intent_id": "explain_typescript", "query": "Explain the benefits of TypeScript",
     "response": "TypeScript adds static type checking to JavaScript, catching errors at compile time instead of runtime. It provides interfaces and type aliases for defining data shapes, generics for reusable typed components, and enums for named constants. IDE support improves dramatically — autocomplete, refactoring, and inline documentation become precise. TypeScript supports union types (string | number), intersection types, conditional types, and utility types (Partial, Pick, Omit). It compiles to JavaScript, so it runs everywhere JS does. Large codebases benefit most: types serve as documentation, refactoring is safer, and onboarding is faster. Configuration via tsconfig.json controls strictness levels."},
    {"intent_id": "explain_rust_ownership", "query": "Explain Rust's ownership system",
     "response": "Rust's ownership system manages memory without garbage collection through three rules: each value has exactly one owner, only one owner at a time, and when the owner goes out of scope the value is dropped. Borrowing allows temporary references: immutable borrows (&T, unlimited simultaneous) and mutable borrows (&mut T, exclusive). The borrow checker enforces these at compile time, preventing data races, dangling pointers, and use-after-free bugs. Lifetimes annotate how long references are valid. Move semantics transfer ownership instead of copying. This system provides memory safety and thread safety with zero runtime cost, making Rust ideal for systems programming, WebAssembly, and performance-critical applications."},

    # ── PRACTICAL TIPS (short / detailed) ─────────────────────────────
    {"intent_id": "tip_naming", "query": "Give me tips for naming variables",
     "response": "Use descriptive, intention-revealing names: user_count not uc. Boolean variables should read as questions: is_active, has_permission. Functions should be verbs: calculate_total, fetch_users. Avoid abbreviations except widely known ones (URL, ID, HTTP). Use consistent casing: snake_case for Python, camelCase for JavaScript. Avoid single-letter names except in tiny scopes (loop counter i). Name collections as plurals: users, order_items. Avoid generic names like data, info, temp, result unless scope is very small."},
    {"intent_id": "tip_debugging", "query": "Give me debugging tips",
     "response": "Read the error message carefully — it usually tells you exactly what's wrong and where. Reproduce the bug consistently before trying to fix it. Use a debugger with breakpoints instead of print statements for complex issues. Rubber duck debugging: explain the problem out loud step by step. Check recent changes with 'git diff' or 'git log'. Simplify: remove code until the bug disappears, then add back to isolate. Check your assumptions — log the actual values of variables you think you know. Search the exact error message. Write a failing test that reproduces the bug before fixing it."},

    # ── WEB (detailed / list) ─────────────────────────────────────────
    {"intent_id": "explain_cookies_sessions", "query": "Explain how cookies and sessions work",
     "response": "Cookies are small pieces of data stored in the browser and sent with every HTTP request to the same domain. The server sets cookies via the Set-Cookie header with attributes: Domain, Path, Expires/Max-Age, Secure (HTTPS only), HttpOnly (no JavaScript access), and SameSite (CSRF protection). Sessions use cookies to store a session ID that maps to server-side data (in memory, Redis, or a database). When a user logs in, the server creates a session, stores user data server-side, and sends the session ID as a cookie. On each request, the server looks up the session ID to retrieve user state. Sessions are more secure since sensitive data stays server-side."},
    {"intent_id": "list_status_codes", "query": "List important HTTP status codes",
     "response": "1. 200 OK — successful request\n2. 201 Created — resource successfully created\n3. 204 No Content — success with no response body\n4. 301 Moved Permanently — resource URL changed permanently\n5. 304 Not Modified — cached version is still valid\n6. 400 Bad Request — malformed request syntax\n7. 401 Unauthorized — authentication required\n8. 403 Forbidden — authenticated but insufficient permissions\n9. 404 Not Found — resource doesn't exist\n10. 429 Too Many Requests — rate limit exceeded\n11. 500 Internal Server Error — unexpected server failure\n12. 502 Bad Gateway — upstream server returned invalid response\n13. 503 Service Unavailable — server temporarily overloaded"},

    # ── FILL TO 100 ───────────────────────────────────────────────────
    {"intent_id": "explain_oauth", "query": "Explain how OAuth 2.0 works",
     "response": "OAuth 2.0 allows users to grant third-party applications limited access to their resources without sharing passwords. The flow: the app redirects the user to the authorization server (Google, GitHub). The user logs in and consents to specific scopes (read email, access repos). The authorization server redirects back with an authorization code. The app exchanges this code (plus its client secret) for an access token. The app uses this token in API requests via the Authorization header. Tokens expire and can be refreshed using refresh tokens. Common grant types: Authorization Code (web apps), PKCE (mobile/SPA), Client Credentials (server-to-server), and Implicit (deprecated)."},
    {"intent_id": "explain_websockets", "query": "Explain how WebSockets work",
     "response": "WebSockets provide full-duplex, persistent communication between client and server over a single TCP connection. The connection starts as an HTTP request with an Upgrade header. If the server accepts, it responds with 101 Switching Protocols, and the connection is upgraded from HTTP to WebSocket. Both sides can then send messages at any time without the overhead of HTTP headers. This is ideal for real-time applications: chat, live notifications, collaborative editing, gaming, and financial tickers. The WebSocket API in JavaScript uses new WebSocket(url), with onopen, onmessage, onclose, and onerror event handlers. Libraries like Socket.IO add features like auto-reconnection and room-based broadcasting."},
    {"intent_id": "list_testing_frameworks", "query": "List popular testing frameworks",
     "response": "1. pytest — Python, powerful fixtures and plugins\n2. Jest — JavaScript/TypeScript, built-in mocking\n3. JUnit — Java, the standard unit testing framework\n4. RSpec — Ruby, behavior-driven development\n5. Go testing — Go, built into the standard library\n6. Playwright — cross-browser end-to-end testing\n7. Cypress — JavaScript E2E testing with time travel\n8. Mocha — JavaScript, flexible with any assertion library\n9. xUnit — .NET, modern testing framework\n10. Catch2 — C++, header-only testing framework"},
    {"intent_id": "explain_caching_strategies", "query": "Explain caching strategies",
     "response": "Cache-Aside (Lazy Loading): application checks cache first, loads from DB on miss, writes to cache. Simple but can have cache stampede. Write-Through: writes go to cache and DB simultaneously, ensuring consistency but adding write latency. Write-Behind (Write-Back): writes go to cache immediately, asynchronously synced to DB — faster writes but risk of data loss. Read-Through: cache itself loads from DB on miss, transparent to application. TTL-Based: entries expire after a time period, balancing freshness and hit rate. Cache Invalidation: actively remove stale entries on data changes. Use Redis or Memcached for distributed caching. CDNs cache static assets at the edge for geographic performance."},
    {"intent_id": "explain_hashing", "query": "Explain how hashing works",
     "response": "A hash function takes input of any size and produces a fixed-size output (hash/digest). Good hash functions are deterministic (same input → same output), fast to compute, produce uniformly distributed outputs, and are one-way (can't reverse the hash to find the input). Cryptographic hashes (SHA-256, bcrypt) add collision resistance — it's computationally infeasible to find two inputs with the same hash. Uses: password storage (hash + salt), data integrity verification (checksums), hash tables (fast key-value lookup), digital signatures, and blockchain. For passwords, use slow hashes like bcrypt or Argon2 with unique salts to resist brute-force attacks."},
    {"intent_id": "list_api_auth_methods", "query": "What are the API authentication methods?",
     "response": "1. API Keys — simple token in header or query parameter\n2. Basic Auth — base64-encoded username:password in header\n3. Bearer Tokens — JWT or opaque tokens in Authorization header\n4. OAuth 2.0 — delegated authorization with access tokens\n5. Session Cookies — server-side session with cookie ID\n6. HMAC Signatures — signed requests with shared secret\n7. mTLS — mutual TLS with client certificates\n8. OpenID Connect — identity layer on top of OAuth 2.0\n9. SAML — XML-based SSO for enterprise applications\n10. Hawk — HTTP MAC-based authentication"},
    {"intent_id": "explain_solid", "query": "Explain the SOLID principles",
     "response": "SOLID is five principles for maintainable object-oriented design. Single Responsibility: each class should have one reason to change — separate concerns into focused classes. Open/Closed: classes should be open for extension but closed for modification — use interfaces and inheritance to add behavior. Liskov Substitution: subclasses must be usable wherever their parent class is expected without breaking behavior. Interface Segregation: prefer many small, specific interfaces over one large interface — clients shouldn't depend on methods they don't use. Dependency Inversion: high-level modules should depend on abstractions, not concrete implementations — inject dependencies rather than creating them internally. Together, these principles reduce coupling, improve testability, and make code easier to modify."},
    {"intent_id": "list_git_commands", "query": "List essential Git commands",
     "response": "1. git init — initialize a new repository\n2. git clone — copy a remote repository locally\n3. git add — stage changes for commit\n4. git commit — save staged changes with a message\n5. git push — upload commits to remote\n6. git pull — fetch and merge remote changes\n7. git branch — list, create, or delete branches\n8. git checkout / git switch — switch branches\n9. git merge — combine branches\n10. git rebase — replay commits onto a new base\n11. git stash — temporarily save uncommitted changes\n12. git log — view commit history\n13. git diff — show changes between commits or working tree\n14. git reset — undo commits or unstage files"},
    {"intent_id": "explain_dns_records", "query": "Explain the types of DNS records",
     "response": "A records map a domain to an IPv4 address (e.g., example.com → 93.184.216.34). AAAA records map to IPv6 addresses. CNAME records create aliases pointing one domain to another (blog.example.com → example.com). MX records specify mail servers for a domain with priority values. TXT records hold arbitrary text, used for email verification (SPF, DKIM, DMARC) and domain ownership proof. NS records delegate a subdomain to specific nameservers. SOA records contain zone authority information (primary nameserver, admin email, serial number). SRV records specify service locations with port and priority. CAA records control which CAs can issue certificates for the domain. PTR records map IP addresses back to domain names (reverse DNS)."},
    {"intent_id": "explain_agile", "query": "Explain Agile methodology",
     "response": "Agile is an iterative approach to software development that delivers working software in short cycles called sprints (typically 1-4 weeks). Core practices include: Sprint Planning (team selects work from a prioritized backlog), Daily Standups (brief sync on progress and blockers), Sprint Review (demo completed work to stakeholders), and Retrospectives (reflect on process improvements). User Stories describe features from the user's perspective with acceptance criteria. The Product Owner prioritizes the backlog based on business value. The Scrum Master facilitates the process and removes obstacles. Key principles from the Agile Manifesto: individuals over processes, working software over documentation, customer collaboration over contracts, and responding to change over following a plan."},
    {"intent_id": "list_python_libs", "query": "List essential Python libraries",
     "response": "1. requests — HTTP client for API calls\n2. FastAPI / Flask / Django — web frameworks\n3. SQLAlchemy — database ORM and toolkit\n4. pandas — data manipulation and analysis\n5. NumPy — numerical computing with arrays\n6. pytest — testing framework\n7. Pydantic — data validation with type hints\n8. Celery — distributed task queue\n9. BeautifulSoup / Scrapy — web scraping\n10. Pillow — image processing\n11. Click / Typer — CLI application frameworks\n12. asyncio / httpx — async programming and HTTP"},
    {"intent_id": "explain_rate_limiting", "query": "Explain how rate limiting works",
     "response": "Rate limiting controls how many requests a client can make in a time window to protect servers from abuse and ensure fair usage. Common algorithms: Token Bucket — a bucket fills with tokens at a fixed rate; each request consumes a token; requests are rejected when the bucket is empty, allowing short bursts. Sliding Window — counts requests in a rolling time window, providing smoother limiting than fixed windows. Leaky Bucket — requests queue up and are processed at a constant rate, smoothing traffic spikes. Fixed Window — simple counter per time interval that resets at boundaries. Implementation: track requests per API key or IP in Redis with TTL-based counters. Return 429 Too Many Requests with Retry-After header when limits are exceeded."},

    # ── ADDITIONAL TO REACH 100 ───────────────────────────────────────
    {"intent_id": "explain_graphql_schema", "query": "Explain GraphQL schemas and resolvers",
     "response": "A GraphQL schema defines the API's type system using SDL (Schema Definition Language). Types describe data shapes: scalar types (String, Int, Boolean), object types (User, Post), and special root types (Query, Mutation, Subscription). Each field on a type has a resolver — a function that fetches the data for that field. When a query arrives, GraphQL parses it against the schema, validates it, then executes resolvers for each requested field. Resolvers can fetch from databases, APIs, or any data source. The schema serves as a contract between frontend and backend, enabling tooling like auto-generated documentation, type-safe clients, and IDE autocomplete."},
    {"intent_id": "explain_middleware", "query": "Explain how middleware works in web frameworks",
     "response": "Middleware are functions that sit between the incoming request and the route handler, forming a processing pipeline. Each middleware receives the request, can modify it, perform actions (logging, authentication, rate limiting), and either pass it to the next middleware or short-circuit with a response. The chain runs in order: request flows down through middleware, hits the route handler, then the response flows back up. Common uses: CORS headers, request body parsing, session management, error handling, and compression. In Express.js, middleware uses app.use(fn). In FastAPI, you decorate with @app.middleware('http'). In Django, middleware classes implement process_request and process_response methods."},
    {"intent_id": "list_css_frameworks", "query": "List popular CSS frameworks",
     "response": "1. Tailwind CSS — utility-first with composable classes\n2. Bootstrap — component-based with pre-built UI elements\n3. Bulma — modern flexbox-based framework\n4. Foundation — responsive enterprise framework\n5. Material UI — Google's Material Design for React\n6. Chakra UI — accessible component library for React\n7. Ant Design — enterprise UI design system\n8. DaisyUI — Tailwind component library\n9. Sass/SCSS — CSS preprocessor with variables and nesting\n10. Styled Components — CSS-in-JS for React"},
    {"intent_id": "explain_promises", "query": "Explain JavaScript Promises and async patterns",
     "response": "A Promise represents a value that may not be available yet. It has three states: pending (initial), fulfilled (resolved with a value), or rejected (failed with an error). Create one with new Promise((resolve, reject) => {...}). Chain operations with .then(onFulfilled) and handle errors with .catch(onRejected). .finally() runs regardless of outcome. Promise.all() waits for multiple promises to complete; Promise.race() resolves with the first to settle; Promise.allSettled() waits for all regardless of success/failure. Async/await is syntactic sugar: 'async function' returns a Promise, and 'await' pauses execution until the Promise resolves, making asynchronous code read like synchronous code. Use try/catch for error handling with await."},
    {"intent_id": "fact_json", "query": "What is JSON?", "response": "JSON (JavaScript Object Notation) is a lightweight text format for structured data exchange, using key-value pairs and arrays. It's language-independent and widely used in APIs and configuration files."},
    {"intent_id": "fact_yaml", "query": "What is YAML?", "response": "YAML (YAML Ain't Markup Language) is a human-readable data serialization format using indentation for structure. It's commonly used for configuration files in Docker, Kubernetes, CI/CD pipelines, and Ansible."},
    {"intent_id": "explain_redis", "query": "Explain how Redis works",
     "response": "Redis is an in-memory data structure store used as a database, cache, and message broker. It stores data in RAM for sub-millisecond read/write latency. Supported data structures include strings, hashes, lists, sets, sorted sets, streams, and bitmaps. Redis is single-threaded, using an event loop to handle concurrent connections without locks. Persistence options include RDB snapshots (periodic point-in-time saves) and AOF (append-only file logging every write). Redis Cluster provides horizontal scaling by sharding data across multiple nodes. Common use cases: session storage, caching, real-time leaderboards, rate limiting, pub/sub messaging, and distributed locks."},
    {"intent_id": "explain_containers", "query": "Explain how containers work at a low level",
     "response": "Containers use Linux kernel features to isolate processes without a full VM. Namespaces provide isolation: PID namespace gives containers their own process tree, network namespace provides separate network stacks, mount namespace isolates filesystems, and UTS namespace allows unique hostnames. Cgroups (control groups) limit resource usage — CPU, memory, I/O, and network bandwidth per container. Union filesystems (OverlayFS) layer read-only image layers with a writable container layer on top, enabling efficient storage and fast startup. The container runtime (containerd, CRI-O) manages the lifecycle. Images are built from Dockerfiles as ordered layers, cached and shared across containers for efficiency."},
    {"intent_id": "list_vim_commands", "query": "List essential Vim commands",
     "response": "1. i — enter insert mode\n2. Esc — return to normal mode\n3. :w — save file\n4. :q — quit (:q! force quit, :wq save and quit)\n5. dd — delete line, yy — copy line, p — paste\n6. / — search forward, n — next match\n7. u — undo, Ctrl+r — redo\n8. gg — go to top, G — go to bottom\n9. :s/old/new/g — replace in line, :%s/old/new/g — replace in file\n10. v — visual select, > — indent, < — unindent\n11. ciw — change inner word, ci\" — change inside quotes\n12. :split / :vsplit — split windows"},
    {"intent_id": "explain_map_reduce", "query": "Explain MapReduce",
     "response": "MapReduce is a programming model for processing large datasets across a distributed cluster in two phases. The Map phase takes input data, splits it into chunks distributed across worker nodes, and applies a mapping function that emits key-value pairs. For example, counting words: each mapper emits (word, 1) for every word it sees. The Shuffle phase groups all values by key and distributes them to reducers. The Reduce phase aggregates values for each key — for word count, summing all the 1s for each word. This model handles fault tolerance by re-running failed tasks. Hadoop popularized MapReduce, though modern frameworks like Spark offer faster in-memory alternatives with richer APIs."},
    {"intent_id": "explain_cap_theorem", "query": "Explain the CAP theorem",
     "response": "The CAP theorem states that a distributed system can provide at most two of three guarantees simultaneously: Consistency (every read returns the most recent write), Availability (every request receives a response), and Partition Tolerance (the system continues operating despite network partitions). Since network partitions are inevitable in distributed systems, the real choice is between CP and AP. CP systems (like HBase, MongoDB with majority writes) sacrifice availability during partitions to maintain consistency. AP systems (like Cassandra, DynamoDB) remain available but may return stale data. Many modern systems offer tunable consistency, letting you choose per-operation based on your needs."},
    {"intent_id": "explain_functional", "query": "Explain functional programming concepts",
     "response": "Functional programming treats computation as evaluation of mathematical functions, avoiding mutable state and side effects. Pure functions always return the same output for the same input with no side effects. Immutability means data structures are never modified — new versions are created instead. First-class functions can be passed as arguments, returned from other functions, and assigned to variables. Higher-order functions like map, filter, and reduce transform collections declaratively. Composition chains small functions into complex pipelines. Closures capture surrounding state. Pattern matching destructures data elegantly. Monads (like Option/Maybe) handle effects in a composable way. Languages: Haskell (pure), Scala, Elixir, Clojure; features adopted in Python, JavaScript, Rust."},
    {"intent_id": "list_machine_learning", "query": "List types of machine learning algorithms",
     "response": "1. Linear Regression — predicts continuous values\n2. Logistic Regression — binary classification\n3. Decision Trees — tree-based splitting rules\n4. Random Forest — ensemble of decision trees\n5. Support Vector Machines — finds optimal separating hyperplane\n6. K-Nearest Neighbors — classifies by proximity\n7. K-Means Clustering — unsupervised grouping\n8. Neural Networks — deep learning with layers of neurons\n9. Gradient Boosting (XGBoost, LightGBM) — sequential ensemble\n10. Naive Bayes — probabilistic classifier\n11. Principal Component Analysis — dimensionality reduction\n12. Reinforcement Learning — learns through reward signals"},
    {"intent_id": "explain_garbage_collection", "query": "Explain how garbage collection works",
     "response": "Garbage collection (GC) automatically reclaims memory occupied by objects no longer reachable from the program's root references. Mark-and-Sweep is the basic approach: the GC traverses all references from root objects (global variables, stack), marking reachable objects as alive, then sweeps through the heap freeing unmarked objects. Generational GC optimizes this by separating objects into generations — most objects die young, so the young generation is collected frequently and quickly, while older generations are collected less often. Java's G1 GC divides the heap into regions for parallel collection. Python uses reference counting (instant cleanup when count hits zero) plus a cycle detector for circular references. Go uses a concurrent tri-color mark-and-sweep with very low pause times."},
    {"intent_id": "fact_ascii", "query": "What is ASCII?", "response": "ASCII (American Standard Code for Information Interchange) is a 7-bit character encoding standard representing 128 characters: English letters, digits, punctuation, and control characters. Extended ASCII uses 8 bits for 256 characters. Unicode (UTF-8) supersedes ASCII while remaining backwards-compatible."},
    {"intent_id": "explain_message_queues", "query": "Explain message queues and when to use them",
     "response": "Message queues enable asynchronous communication between services by storing messages in a buffer until consumers process them. Producers send messages to a queue; consumers pull messages at their own pace. This decouples services — the producer doesn't wait for the consumer, and either can scale independently. Key patterns: point-to-point (one consumer per message) and pub/sub (multiple consumers receive copies). Use message queues for: background job processing (email sending, image resizing), smoothing traffic spikes, ensuring delivery of critical operations, and cross-service communication in microservices. Popular systems: RabbitMQ (AMQP protocol, routing flexibility), Apache Kafka (distributed log, high throughput, event streaming), AWS SQS (managed, serverless), and Redis Streams (lightweight, built into Redis)."},
]


async def main():
    # Merge base examples with large template set
    from templates_large import TEMPLATES as LARGE_TEMPLATES

    all_examples = list(EXAMPLES)
    existing_ids = {ex["intent_id"] for ex in EXAMPLES}
    for t in LARGE_TEMPLATES:
        if t["intent_id"] not in existing_ids:
            all_examples.append({
                "intent_id": t["intent_id"],
                "query": t["query"],
                "response": t["response"],
            })
            existing_ids.add(t["intent_id"])

    intents = set(ex["intent_id"] for ex in all_examples)
    print(f"Seeding {len(all_examples)} query-response pairs ({len(intents)} unique intents)...")

    cache_store = CacheStore()
    router = IntentRouter(cache_store)

    await router.seed_centroids(all_examples)

    # Verify and build clusters
    centroids = cache_store.get_all_intent_centroids()
    print(f"  → {len(centroids)} centroids written to Redis")

    # Build cluster router
    cluster_router = ClusterRouter()
    cluster_router.build(centroids)

    if cluster_router.is_built:
        print(f"  → {cluster_router.cluster_count} clusters built")
        for info in cluster_router.get_cluster_info():
            print(f"    Cluster '{info['label']}': {info['size']} intents")
    else:
        print("  → Clustering skipped (below threshold)")

    print(f"\n✓ Cache seeded with {len(all_examples)} examples across {len(intents)} intents!")


if __name__ == "__main__":
    asyncio.run(main())

